# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: vahidkowsari/buildenv-fe:initial

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - /bin/bash << EOF
          - cd /code--
          - npm -g install grunt-cli karma bower protractor
          - npm install
          - bower --allow-root install
          - grunt build
          - EOF-
